/** Produces the human-maintained contract at the top of every generated file. */
import {agentCommands, maximumAgents} from '../agents.js';
import {usesCaddy, type Settings} from '../settings.js';
import {commentText} from './toml.js';

/** Where the description column starts, measured from after the `#   ` indent. */
const descriptionColumn = 23;

export function generateHeader(settings: Settings): string {
	const lines = [
		'# Worktree automation shared by everyone on this repo.',
		'#',
		`# Generated by trunk ${commentText(settings.trunkVersion)} on ${
			settings.generatedOn
		} — edit it freely; trunk won't touch it again.`,
		'#',
		'# Setup on a new machine: install worktrunk (`wt`) with its shell integration, then run',
		'# `wt config approvals add` here (again whenever this file changes).',
		`# Package manager: ${settings.pm}.`,
	];
	const optionalTools = optionalToolNames(settings);
	if (optionalTools.length > 0) {
		lines.push(
			`# ${joinList(optionalTools)} ${
				optionalTools.length === 1 ? 'is' : 'are'
			} optional; each step skips itself when its tool is missing.`,
		);
	}

	const environment = environmentLines(settings);
	if (environment.length > 0) {
		lines.push(
			'# Each machine can tune the optional steps with env vars in its shell profile:',
			'#',
			...environment,
			'#',
		);
	}

	if (settings.tmux) {
		lines.push(
			"# P is this repo's tmux session prefix; keep it unique across your repos.",
		);
	}

	if (settings.noRemote) {
		lines.push(
			`# No git remote yet, so the repo name is written out below. After you add one`,
			'# (git remote add origin <url>), you can switch these back to',
			'# {{ remote_repo | lower }}.',
		);
	}

	lines.push(
		'# Hook bodies are POSIX sh. Worktrunk template expressions are intentional; avoid',
		'# introducing shell forms that collide with them (notably shell length expansion).',
	);

	return lines.join('\n');
}

function optionalToolNames(settings: Settings): string[] {
	const names: string[] = [];
	if (settings.tmux) {
		names.push('tmux');
	}

	if (usesCaddy(settings)) {
		names.push('caddy');
	}

	for (const agent of settings.agents) {
		names.push(agentCommands[agent]);
	}

	return names;
}

function environmentLines(settings: Settings): string[] {
	const lines: string[] = [];
	if (settings.tmux) {
		lines.push(settingLine('WT_TMUX=off', 'no tmux session'));
		if (settings.agents.length > 0) {
			const agents = JSON.stringify(settings.agents.join(' '));
			lines.push(
				settingLine(
					`WT_AGENTS=${agents}`,
					'agents started in the Agents window',
				),
				settingLine(
					'',
					`(default ${agents}; "" starts none; max ${maximumAgents})`,
				),
			);
		}

		lines.push(
			settingLine(
				'WT_EDITOR=hx',
				'editor in the Editor window (default $EDITOR, then nvim)',
			),
		);
	}

	if (usesCaddy(settings)) {
		lines.push(settingLine('WT_PROXY=off', 'no Caddy route'));
	}

	return lines;
}

/**
 * One `VAR=value   description` line. A long value pushes its own description
 * right rather than running into it, so the block stays readable for any agent
 * list.
 */
function settingLine(setting: string, description: string): string {
	const padded =
		setting.length >= descriptionColumn
			? `${setting} `
			: setting.padEnd(descriptionColumn);
	return `#   ${padded}${description}`;
}

function joinList(values: readonly string[]): string {
	if (values.length < 2) {
		return values[0] ?? '';
	}

	if (values.length === 2) {
		return values.join(' and ');
	}

	return `${values.slice(0, -1).join(', ')}, and ${values.at(-1)}`;
}
