import {readFile} from 'node:fs/promises';
import {sep} from 'node:path';
import {afterAll, afterEach, describe, expect, test} from 'bun:test';
import {parseArguments} from '../source/core/arguments.js';
import {compose} from '../source/core/generate/index.js';
import {guardPlatform} from '../source/core/platform.js';
import {exitCodes} from '../source/core/result.js';
import {trunkVersion} from '../source/core/version.js';
import {buildCli, runCli, type CliRun} from './helpers/run.js';
import {testSettings} from './helpers/settings.js';

describe('CLI', () => {
	const build = buildCli();
	const runs: CliRun[] = [];

	afterAll(async () => {
		const cliBuild = await build;
		await cliBuild.cleanup();
	});

	afterEach(async () => {
		await Promise.all(runs.splice(0).map(async run => run.cleanup()));
	});

	test('shows usage without a command', async () => {
		const run = await runBuiltCli();
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.success);
		expect(run.stdout).toContain('Usage');
		expect(run.stdout).toContain('$ trunk clone <url> [dir]');
		expect(run.stderr).toBe('');
	});

	test('shows usage for --help', async () => {
		const run = await runBuiltCli(['--help']);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.success);
		expect(run.stdout).toContain('$ trunk new <name>');
		expect(run.stderr).toBe('');
	});

	test('reports and generates with the package version', async () => {
		const run = await runBuiltCli(['--version']);
		runs.push(run);
		const packageJson = JSON.parse(
			await readFile(new URL('../package.json', import.meta.url), 'utf8'),
		) as {version: string};

		expect(run.exitCode).toBe(exitCodes.success);
		expect(run.stdout.trim()).toBe(packageJson.version);
		expect(trunkVersion()).toBe(packageJson.version);
		expect(compose(testSettings({trunkVersion: trunkVersion()}))).toContain(
			`# Generated by trunk ${packageJson.version} on`,
		);
		expect(run.stderr).toBe('');
	});

	test('asks for flags instead of a form when stdin is a pipe', async () => {
		// The built CLI runs with stdin ignored, which is exactly the shape that
		// used to reach Ink and print a React component stack.
		const run = await runBuiltCli(['new', 'demo']);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.badUsage);
		expect(run.stderr).toContain('--yes');
		expect(run.stderr).not.toContain('Raw mode is not supported');
		expect(run.stderr).not.toContain('component:');
	});

	test('rejects an unknown command', async () => {
		const run = await runBuiltCli(['bogus']);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.badUsage);
		expect(run.stdout).toBe('');
		expect(run.stderr).toContain('unknown command: bogus');
		expect(run.stderr).not.toContain('\u001B[');
	});

	test('rejects a project name GitHub would not accept', async () => {
		const run = await runBuiltCli(['new', 'not valid/name']);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.badUsage);
		expect(run.stderr).toContain('not a valid repository name');
		expect(run.stderr).not.toContain('    at ');
	});

	test('rejects a remote that names no repository', async () => {
		const run = await runBuiltCli([
			'clone',
			'https://example.com/repository.git',
		]);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.badUsage);
		expect(run.stderr).toContain('must contain an owner and repository');
		expect(run.stderr).not.toContain('    at ');
	});

	test('asks for a URL before doing anything', async () => {
		const run = await runBuiltCli(['clone']);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.badUsage);
		expect(run.stderr).toContain('needs a remote URL');
	});

	test('exits 3 with the install hint when required tools are missing', async () => {
		const {cliPath} = await build;
		const run = await runCli(
			cliPath,
			['clone', 'https://example.com/repository.git'],
			{environment: Object.fromEntries([['PATH', '']])},
		);
		runs.push(run);

		expect(run.exitCode).toBe(exitCodes.unsupportedEnvironment);
		expect(run.stderr).toContain('Missing required tools: git, wt');
		expect(run.stderr).toContain('https://worktrunk.dev');
	});

	test('keeps boolean flags tri-state', () => {
		expect(parseArguments(['clone', 'url']).flags.server).toBeUndefined();
		expect(parseArguments(['clone', 'url', '--no-server']).flags.server).toBe(
			false,
		);
		expect(parseArguments(['clone', 'url', '--copy']).flags.copyIgnored).toBe(
			true,
		);
	});

	test('rejects native Windows', () => {
		expect(guardPlatform('win32')).toEqual({
			code: exitCodes.unsupportedEnvironment,
			message: 'trunk supports macOS and Linux (including WSL).',
		});
		expect(guardPlatform('linux')).toBeUndefined();
	});

	test('isolates Worktrunk configuration in the temporary directory', async () => {
		const run = await runBuiltCli(['bogus']);
		runs.push(run);

		expect(run.environment['WORKTRUNK_CONFIG_PATH']).toBe(run.configPath);
		expect(run.configPath.startsWith(`${run.temporaryDirectory}${sep}`)).toBe(
			true,
		);
	});

	async function runBuiltCli(arguments_: readonly string[] = []) {
		const {cliPath} = await build;
		return runCli(cliPath, arguments_);
	}
});
