/**
 * The guide docs/generated-config.md quotes the generator's output verbatim. This keeps
 * those quotes from drifting: every TOML block in the document has to appear,
 * unchanged, in what the generator produces today.
 */
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {describe, expect, test} from 'bun:test';
import {compose} from '../source/core/generate/index.js';
import {testSettings} from './helpers/settings.js';

const documentPath = fileURLToPath(
	new URL('../docs/generated-config.md', import.meta.url),
);

/** The version and date change every run, so both sides use placeholders. */
function normalize(text: string): string {
	return text.replace(
		/Generated by trunk \S+ on (?:\d{4}-\d{2}-\d{2}|<date>)/,
		'Generated by trunk <version> on <date>',
	);
}

function tomlBlocks(markdown: string): string[] {
	return [...markdown.matchAll(/```toml\n([\s\S]*?)\n```/g)].map(
		match => match[1]!,
	);
}

describe('docs/generated-config.md', () => {
	// The settings the document describes.
	const generated = normalize(
		compose(
			testSettings({
				prefix: 'storefront',
				agents: ['claude', 'codex'],
				copyIgnored: true,
				mcAlias: true,
			}),
		),
	);

	test('quotes only what the generator really produces', async () => {
		const blocks = tomlBlocks(await readFile(documentPath, 'utf8'));

		// Header, aliases, copy, tmux start, stop and kill.
		expect(blocks).toHaveLength(6);
		for (const block of blocks) {
			expect(generated, block.split('\n')[0]).toContain(normalize(block));
		}
	});

	test('quotes the blocks in the order they appear in the file', async () => {
		const blocks = tomlBlocks(await readFile(documentPath, 'utf8'));
		const positions = blocks.map(block => generated.indexOf(normalize(block)));

		expect(positions).toEqual([...positions].sort((a, b) => a - b));
		expect(new Set(positions).size).toBe(positions.length);
	});

	test('describes a language-agnostic file', async () => {
		const document = await readFile(documentPath, 'utf8');

		expect(document).not.toMatch(
			/\b(npm|pnpm|yarn|bun|caddy|localhost|hash_port|wt_proxy|dev server)\b/i,
		);
		expect(document).toContain('trunk docs');
		expect(document).toContain('wt config approvals add');
	});
});
