/**
 * `trunk clone <url> [dir]`: the full path from a remote URL to a configured,
 * committed project. Every other command is a variation of this pipeline.
 *
 * Two rules shape the code. Nothing ever changes directory: every git call
 * carries `--git-dir` or `-C`, so the pipeline is safe to run from inside
 * another worktree. And every step records what it is about to create in the
 * journal before acting, so an interrupted run can describe or undo precisely
 * what exists.
 */
import {mkdir, readFile, readdir, realpath, writeFile} from 'node:fs/promises';
import {basename, join, resolve as resolvePath} from 'node:path';
import process from 'node:process';
import type {CliFlags} from '../core/arguments.js';
import {detectPackageManager} from '../core/detect.js';
import type {ToolProbe} from '../core/env.js';
import {compose} from '../core/generate/index.js';
import {
	canOpenPullRequest,
	compareUrl,
	createPullRequest,
	publishCommands,
} from '../core/gh.js';
import {
	addWorktree,
	cloneBare,
	commitPath,
	configureOriginFetch,
	listWorktrees,
	remoteDefaultBranch,
	setHeadBranch,
	type GitOptions,
} from '../core/git.js';
import {
	Journal,
	resumeCommand,
	undoCommands,
	type UndoCommand,
} from '../core/journal.js';
import {step as reportStep} from '../core/log.js';
import {loadSshAliases, parseRemote, type ParsedRemote} from '../core/repo.js';
import {setupFlagsFromCli} from '../core/resolve.js';
import {
	badUsage,
	exitCodes,
	operationFailed,
	succeed,
	userAborted,
	type Outcome,
} from '../core/result.js';
import {
	runAttached,
	runCommand,
	type AttachedRunner,
	type CommandRunner,
} from '../core/process.js';
import type {Settings} from '../core/settings.js';
import {validateGeneratedConfig} from '../core/validate.js';
import {trunkVersion} from '../core/version.js';
import {
	approvalsAdd,
	hookLogPath,
	runHook,
	switchAttached,
	switchCreateAttached,
} from '../core/wt.js';
import {collectSettings} from '../ui/SetupForm.js';

export const setupBranch = 'chore/trunk-setup';
export const configPath = '.config/wt.toml';

export const commitMessage = `Add worktree automation

Generated by trunk ${trunkVersion()}: tmux session, dependency install, dev server and
Caddy route for each worktree. Run \`wt config approvals add\` after checking out.`;

export type ClonePrompts = Readonly<{
	/** Returns undefined when the user aborts rather than choosing. */
	choose: (
		question: string,
		options: readonly string[],
	) => Promise<string | undefined>;
	confirm: (question: string) => Promise<boolean | undefined>;
}>;

export type CloneDependencies = Readonly<{
	cwd?: string;
	env?: NodeJS.ProcessEnv;
	run?: CommandRunner;
	attach?: AttachedRunner;
	report?: (
		kind: 'success' | 'error' | 'info' | 'warning',
		line: string,
	) => void;
	interactive?: boolean;
	prompts?: ClonePrompts;
	collect?: typeof collectSettings;
	now?: () => Date;
	invocation?: Readonly<{executable: string; arguments: readonly string[]}>;
}>;

type Context = Readonly<{
	cwd: string;
	env?: NodeJS.ProcessEnv;
	git: GitOptions;
	attach: AttachedRunner;
	run: CommandRunner;
	report: NonNullable<CloneDependencies['report']>;
	interactive: boolean;
	prompts?: ClonePrompts;
	collect: typeof collectSettings;
	now: () => Date;
	invocation: Readonly<{executable: string; arguments: readonly string[]}>;
	tools: ToolProbe;
	flags: CliFlags;
	journal: Journal;
	wtPath: string;
}>;

export async function runClone(
	arguments_: readonly string[],
	flags: CliFlags,
	tools: ToolProbe,
	dependencies: CloneDependencies = {},
): Promise<Outcome> {
	const [url, directory, ...extra] = arguments_;
	if (!url) {
		return badUsage('trunk clone needs a remote URL');
	}

	if (extra.length > 0) {
		return badUsage(`unexpected argument: ${extra[0]!}`);
	}

	const context = createContext(flags, tools, dependencies);
	let remote: ParsedRemote;
	try {
		remote = parseRemote(url, await loadSshAliases(), context.cwd);
	} catch (error: unknown) {
		return badUsage(errorMessage(error));
	}

	const projectDirectory = resolvePath(
		context.cwd,
		directory ?? (remote.repo || basename(url)),
	);
	const emptiness = await folderState(projectDirectory);
	if (emptiness === 'occupied') {
		return badUsage(
			`${projectDirectory} already exists and is not empty; choose another folder`,
		);
	}

	try {
		return await pipeline(context, remote, projectDirectory, emptiness);
	} catch (error: unknown) {
		return interrupted(context, projectDirectory, errorMessage(error));
	}
}

async function pipeline(
	context: Context,
	remote: ParsedRemote,
	projectDirectory: string,
	emptiness: 'missing' | 'empty',
): Promise<Outcome> {
	const gitDirectory = join(projectDirectory, '.git');

	// Step 2: the bare clone, which is also what creates the folder.
	if (emptiness === 'missing') {
		context.journal.record({kind: 'folder', path: projectDirectory});
	}

	context.journal.record({kind: 'bare-repo', path: gitDirectory});
	context.report('info', `cloning ${remote.url}`);
	const cloned = await cloneBare(remote.url, gitDirectory, {
		...context.git,
		attach: context.attach,
	});
	if (cloned !== 0) {
		return interrupted(context, projectDirectory, 'git clone failed');
	}

	// Step 3: a bare clone has no fetch refspec, so origin/* would stay empty.
	const configured = await configureOriginFetch(gitDirectory, context.git);
	if (configured.code !== 0) {
		return interrupted(
			context,
			projectDirectory,
			`could not configure the origin refspec: ${outputOf(configured)}`,
		);
	}

	// Step 4: the remote decides the default branch; never assume main.
	const defaultBranch = await remoteDefaultBranch(remote.url, context.git);
	await setHeadBranch(gitDirectory, defaultBranch, context.git);
	context.report('success', `default branch ${defaultBranch}`);

	// Step 5: let wt place the first worktree so it can ask its own question.
	const defaultWorktree = await createFirstWorktree(context, {
		remote,
		projectDirectory,
		gitDirectory,
		branch: defaultBranch,
	});
	if (!defaultWorktree) {
		return interrupted(
			context,
			projectDirectory,
			`could not create the ${defaultBranch} worktree`,
		);
	}

	// Step 6: an existing config belongs to the repo, not to this run.
	const existing = await readExistingConfig(defaultWorktree);
	if (existing !== undefined) {
		const decision = await decideExistingConfig(context);
		if (decision === 'abort') {
			return interrupted(context, projectDirectory, 'aborted');
		}

		if (decision === 'keep') {
			context.report('info', 'wt.toml exists → kept');
			return finish(context, projectDirectory, defaultWorktree, defaultBranch);
		}
	}

	// Step 7: detection and resolution happen inside the default worktree.
	const detection = await detectPackageManager(defaultWorktree);
	for (const warning of detection.warnings) {
		context.report('warning', warning);
	}

	const collected = await context.collect({
		folder: defaultWorktree,
		resolveOptions: {
			fixed: {
				trunkVersion: trunkVersion(),
				generatedOn: today(context.now()),
				repoName: remote.repo,
				hostLabel: remote.repo.toLowerCase(),
				appDir: detection.appDir,
				scripts: detection.scripts,
			},
			flags: setupFlagsFromCli(context.flags),
			packageDetection: detection,
			tools: context.tools,
		},
		invocation: context.invocation,
		yes: context.flags.yes ?? false,
		interactive: context.interactive,
	});
	if (collected.kind === 'outcome') {
		return collected.outcome.code === exitCodes.userAborted
			? interrupted(context, projectDirectory, 'aborted')
			: collected.outcome;
	}

	return setUpBranch(context, {
		remote,
		projectDirectory,
		gitDirectory,
		defaultWorktree,
		settings: collected.settings,
	});
}

/**
 * Steps 8 to 10: create the worktree that receives the config, write it, let wt
 * check it, and only then commit. Split out of the pipeline because it is the
 * part that touches the repository's history.
 */
async function setUpBranch(
	context: Context,
	plan: Readonly<{
		remote: ParsedRemote;
		projectDirectory: string;
		gitDirectory: string;
		defaultWorktree: string;
		settings: Settings;
	}>,
): Promise<Outcome> {
	const {remote, projectDirectory, gitDirectory, defaultWorktree, settings} =
		plan;

	// The config is unapproved until it is reviewed, so the worktree that
	// receives it is created without hooks.
	const direct = context.flags.direct ?? false;
	const target = direct
		? defaultWorktree
		: join(projectDirectory, setupBranch.replaceAll('/', '-'));
	if (!direct) {
		context.journal.record({
			kind: 'branch-worktree',
			path: target,
			branch: setupBranch,
			note: 'wt.toml uncommitted',
		});
		const created = await createSetupWorktree(
			context,
			projectDirectory,
			gitDirectory,
			target,
		);
		if (created !== 0) {
			return interrupted(
				context,
				projectDirectory,
				`could not create the ${setupBranch} worktree`,
			);
		}
	}

	let worktree = defaultWorktree;
	if (!direct) {
		worktree = await locateWorktree(gitDirectory, target, context.git);
		if (worktree !== target) {
			context.journal.relocate(target, worktree);
			warnAboutWorktreePath(context, remote, worktree);
		}
	}

	// Write, then let wt check its own file before anything is committed.
	await writeConfig(worktree, settings);
	context.report('success', `wrote ${configPath}`);
	try {
		const validation = await validateGeneratedConfig(worktree, settings, {
			wtPath: context.wtPath,
			env: context.env,
		});
		reportPreview(context, validation.preview);
	} catch (error: unknown) {
		return interrupted(context, projectDirectory, errorMessage(error));
	}

	const shouldCommit = await confirmStep(
		context,
		'commit the generated config?',
	);
	if (shouldCommit === undefined) {
		return interrupted(context, projectDirectory, 'aborted');
	}

	if (!shouldCommit) {
		return interrupted(context, projectDirectory, 'left uncommitted');
	}

	const committed = await commitPath(
		worktree,
		configPath,
		commitMessage,
		context.git,
	);
	if (committed.code !== 0) {
		return interrupted(
			context,
			projectDirectory,
			`commit failed: ${outputOf(committed)}`,
		);
	}

	context.journal.annotate(worktree, 'wt.toml committed');
	context.report('success', 'committed the generated config');
	await publish(context, remote, worktree, direct ? undefined : setupBranch);

	return finish(context, projectDirectory, worktree, setupBranch);
}

/**
 * Worktrunk owns worktree placement, so the attached call is the one that gets
 * it right. Without a terminal it cannot ask, so trunk falls back to plain git and
 * says what that will cost.
 */
async function createFirstWorktree(
	context: Context,
	location: Readonly<{
		remote: ParsedRemote;
		projectDirectory: string;
		gitDirectory: string;
		branch: string;
	}>,
): Promise<string | undefined> {
	const {remote, projectDirectory, gitDirectory, branch} = location;
	const expected = join(projectDirectory, branch.replaceAll('/', '-'));
	context.journal.record({kind: 'worktree', path: expected, branch});

	if (context.interactive) {
		await switchAttached(projectDirectory, branch, {
			wtPath: context.wtPath,
			attach: context.attach,
			env: context.env,
		});
	} else {
		const added = await addWorktree(
			gitDirectory,
			expected,
			branch,
			context.git,
		);
		if (added.code !== 0) {
			return undefined;
		}

		warnAboutWorktreePath(context, remote, expected);
	}

	const actual = await locateWorktree(gitDirectory, expected, context.git);
	if (actual !== expected) {
		warnAboutWorktreePath(context, remote, actual);
	}

	return actual;
}

/**
 * Interactive runs let wt place the worktree, the same way the first one is
 * placed. Without a terminal wt cannot ask where worktrees belong and would
 * fall back to `.git.<branch>`, so plain git keeps the sibling layout whole.
 */
async function createSetupWorktree(
	context: Context,
	projectDirectory: string,
	gitDirectory: string,
	target: string,
): Promise<number> {
	if (context.interactive) {
		return switchCreateAttached(projectDirectory, setupBranch, {
			wtPath: context.wtPath,
			attach: context.attach,
			env: context.env,
		});
	}

	const added = await addWorktree(gitDirectory, target, setupBranch, {
		...context.git,
		createBranch: true,
	});
	return added.code ?? 1;
}

function warnAboutWorktreePath(
	context: Context,
	remote: ParsedRemote,
	actual: string,
): void {
	for (const line of worktreePathWarning(remote.identifier, actual)) {
		context.report('warning', line);
	}
}

/** Spelled out because the fix belongs in the user's config, not in trunk's. */
export function worktreePathWarning(
	identifier: string,
	actualPath: string,
): readonly string[] {
	return Object.freeze([
		`worktree-path is not configured for ${identifier}.`,
		`  Agents and scripts will create ${actualPath} instead of a sibling worktree.`,
		'  Fix: run `wt switch <branch>` in a terminal once, or add to ~/.config/worktrunk/config.toml:',
		`    [projects."${identifier}"]`,
		'    worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"',
	]);
}

/**
 * Where a worktree actually landed. git reports resolved paths, so on a system
 * where a temp or home directory is a symlink the string trunk proposed and the
 * string git prints differ; both sides are resolved before comparing.
 */
async function locateWorktree(
	gitDirectory: string,
	expected: string,
	options: GitOptions,
): Promise<string> {
	const worktrees = await listWorktrees(gitDirectory, options);
	const target = await canonicalPath(expected);
	const resolved = await Promise.all(
		worktrees.map(async path => [path, await canonicalPath(path)] as const),
	);
	const match = resolved.find(([, canonical]) => canonical === target);
	if (match) {
		return match[0];
	}

	// Worktrunk may have placed it beside the git directory instead; the last
	// entry is the one just added.
	return worktrees.at(-1) ?? expected;
}

async function canonicalPath(path: string): Promise<string> {
	try {
		return await realpath(path);
	} catch {
		return path;
	}
}

async function decideExistingConfig(
	context: Context,
): Promise<'keep' | 'overwrite' | 'abort'> {
	if (!context.interactive || (context.flags.yes ?? false)) {
		return 'keep';
	}

	const answer = await context.prompts?.choose(
		`${configPath} already exists. Keep it, or overwrite with the generated one?`,
		['keep', 'overwrite'],
	);
	if (answer === undefined) {
		return 'abort';
	}

	return answer === 'overwrite' ? 'overwrite' : 'keep';
}

async function confirmStep(
	context: Context,
	question: string,
): Promise<boolean | undefined> {
	if (!context.interactive || (context.flags.yes ?? false)) {
		return true;
	}

	return context.prompts?.confirm(question) ?? true;
}

/**
 * Publishing is opt-in without a terminal: `--yes` alone stops after the commit
 * and prints the commands, so a scripted run never pushes by surprise.
 */
async function publish(
	context: Context,
	remote: ParsedRemote,
	worktree: string,
	branch: string | undefined,
): Promise<void> {
	if (!branch) {
		return;
	}

	const withPullRequest = canOpenPullRequest(
		remote,
		context.tools.gh.path !== undefined,
	);
	const wanted =
		context.flags.yes ?? false
			? false
			: await confirmStep(context, 'push and open a pull request?');
	if (!wanted) {
		for (const command of publishCommands(branch, withPullRequest)) {
			context.report('info', command);
		}

		const url = compareUrl(remote, branch);
		if (url && !withPullRequest) {
			context.report('info', url);
		}

		return;
	}

	const pushed = await context.run(
		context.git.gitPath ?? 'git',
		['-C', worktree, 'push', '-u', 'origin', branch],
		{env: context.env},
	);
	if (pushed.code !== 0) {
		context.report('error', `push failed: ${outputOf(pushed)}`);
		return;
	}

	if (!withPullRequest) {
		const url = compareUrl(remote, branch);
		if (url) {
			context.report('info', url);
		}

		return;
	}

	const pullRequest = await createPullRequest(worktree, {
		ghPath: context.tools.gh.path,
		run: context.run,
		env: context.env,
	});
	context.report(
		pullRequest.code === 0 ? 'success' : 'error',
		outputOf(pullRequest),
	);
}

/** Step 11: approvals and the smoke test, both optional and both attached. */
async function finish(
	context: Context,
	projectDirectory: string,
	worktree: string,
	branch: string,
): Promise<Outcome> {
	if (!context.interactive || (context.flags.yes ?? false)) {
		context.report('info', `next: wt config approvals add (in ${worktree})`);
		return succeed(`set up ${projectDirectory}`);
	}

	const approve = await confirmStep(
		context,
		'run `wt config approvals add` now?',
	);
	if (approve) {
		await approvalsAdd(worktree, {
			wtPath: context.wtPath,
			attach: context.attach,
			env: context.env,
		});
	}

	context.report(
		'info',
		'the smoke test starts a real dev server and Caddy route; stop them with `wt remove` or the `up` alias',
	);
	const smoke = await confirmStep(
		context,
		'run the hooks once as a smoke test?',
	);
	if (!smoke) {
		return succeed(`set up ${projectDirectory}`);
	}

	for (const hook of ['pre-start', 'post-start'] as const) {
		// eslint-disable-next-line no-await-in-loop
		const code = await runHook(worktree, hook, {
			wtPath: context.wtPath,
			attach: context.attach,
			env: context.env,
		});
		if (code !== 0) {
			context.report('error', `${hook} failed`);
			context.report('info', hookLogPath(projectDirectory, branch, hook));
			return operationFailed(`${hook} failed in ${worktree}`);
		}
	}

	return succeed(`set up ${projectDirectory}`);
}

/**
 * Step 12. Every failure and abort lands here, where the journal turns into
 * either a resume hint or a precise undo.
 */
async function interrupted(
	context: Context,
	projectDirectory: string,
	reason: string,
): Promise<Outcome> {
	context.report('error', reason);
	if (context.journal.isEmpty) {
		return operationFailed(reason);
	}

	context.report('info', 'created by this run:');
	for (const line of context.journal.describe(context.cwd)) {
		context.report('info', `  ${line}`);
	}

	const undo = undoCommands(
		context.journal,
		projectDirectory,
		context.wtPath,
		context.git.gitPath ?? 'git',
	);
	const choice = context.interactive
		? await context.prompts?.choose(
				'keep, or roll back what this run created?',
				['keep', 'rollback'],
		  )
		: 'keep';

	if (choice === 'rollback') {
		await rollback(context, undo);
		return userAborted(`rolled back ${projectDirectory}`);
	}

	context.report(
		'info',
		`resume: ${resumeCommand(projectDirectory, context.cwd)}`,
	);
	for (const command of undo) {
		context.report('info', `  ${describeUndo(command)}`);
	}

	return operationFailed(reason);
}

async function rollback(
	context: Context,
	commands: readonly UndoCommand[],
): Promise<void> {
	for (const command of commands) {
		// Rollback is ordered newest first, so the steps cannot run in parallel.
		// eslint-disable-next-line no-await-in-loop
		const result = await context.run(command.executable, command.arguments, {
			env: context.env,
		});
		context.report(
			result.code === 0 ? 'success' : 'warning',
			`${command.purpose}${
				result.code === 0 ? '' : ` — failed: ${outputOf(result)}`
			}`,
		);
	}
}

function describeUndo(command: UndoCommand): string {
	return `${command.executable} ${command.arguments.join(' ')}   # ${
		command.purpose
	}`;
}

async function writeConfig(
	worktree: string,
	settings: Settings,
): Promise<void> {
	await mkdir(join(worktree, '.config'), {recursive: true});
	await writeFile(join(worktree, configPath), compose(settings));
}

async function readExistingConfig(
	worktree: string,
): Promise<string | undefined> {
	try {
		return await readFile(join(worktree, configPath), 'utf8');
	} catch {
		return undefined;
	}
}

function reportPreview(
	context: Context,
	preview: Readonly<{session?: string; port?: number; url?: string}>,
): void {
	for (const [label, value] of [
		['session', preview.session],
		['port', preview.port],
		['url', preview.url],
	] as const) {
		if (value !== undefined) {
			context.report('info', `${label} ${value}`);
		}
	}
}

async function folderState(
	path: string,
): Promise<'missing' | 'empty' | 'occupied'> {
	try {
		const entries = await readdir(path);
		return entries.every(entry => ignorable.has(entry)) ? 'empty' : 'occupied';
	} catch {
		return 'missing';
	}
}

const ignorable = new Set(['.DS_Store', '.localized', 'Thumbs.db']);

function createContext(
	flags: CliFlags,
	tools: ToolProbe,
	dependencies: CloneDependencies,
): Context {
	const report =
		dependencies.report ??
		((kind, line) => {
			reportStep(kind, line);
		});
	return {
		cwd: dependencies.cwd ?? process.cwd(),
		env: dependencies.env,
		git: {gitPath: tools.git.path, run: dependencies.run},
		attach: dependencies.attach ?? runAttached,
		run: dependencies.run ?? runCommand,
		report,
		interactive:
			dependencies.interactive ??
			(Boolean(process.stdin.isTTY) && !(flags.yes ?? false)),
		prompts: dependencies.prompts,
		collect: dependencies.collect ?? collectSettings,
		now: dependencies.now ?? (() => new Date()),
		invocation: dependencies.invocation ?? {
			executable: 'trunk',
			arguments: process.argv.slice(2),
		},
		tools,
		flags,
		journal: new Journal(),
		wtPath: tools.wt.path ?? 'wt',
	};
}

function today(date: Date): string {
	return date.toISOString().slice(0, 10);
}

function outputOf(result: Readonly<{stdout: string; stderr: string}>): string {
	return result.stderr.trim() || result.stdout.trim() || 'no output';
}

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}
