import {readFile, rm, writeFile} from 'node:fs/promises';

const packageUrl = new URL('../package.json', import.meta.url);
const packageJson = JSON.parse(await readFile(packageUrl, 'utf8'));
const {version} = packageJson;

if (
	typeof version !== 'string' ||
	!/^\d+\.\d+\.\d+(?:-[\dA-Za-z.-]+)?(?:\+[\dA-Za-z.-]+)?$/.test(version)
) {
	throw new TypeError('package.json must contain a semantic version.');
}

const generated = `/** Generated by scripts/prepare-build.mjs. Do not edit. */
export const version = '${version}';
`;

await Promise.all([
	writeFile(new URL('../source/version.ts', import.meta.url), generated),
	rm(new URL('../dist/', import.meta.url), {recursive: true, force: true}),
]);
