/**
 * Writes `source/version.ts` from package.json.
 *
 * The version has to reach the generated config header, and reading package.json
 * at run time breaks when only `dist` ships. So it is stamped into the source
 * instead — which means every task that compiles or lints the source depends on
 * this having run, not only the build. The file is generated, so it is
 * gitignored, and a clean checkout has to produce it before anything reads it.
 */
import {readFile, writeFile} from 'node:fs/promises';

const packageUrl = new URL('../package.json', import.meta.url);
const packageJson = JSON.parse(await readFile(packageUrl, 'utf8'));
const {version} = packageJson;

if (
	typeof version !== 'string' ||
	!/^\d+\.\d+\.\d+(?:-[\dA-Za-z.-]+)?(?:\+[\dA-Za-z.-]+)?$/.test(version)
) {
	throw new TypeError('package.json must contain a semantic version.');
}

await writeFile(
	new URL('../source/version.ts', import.meta.url),
	`/** Generated by scripts/stamp-version.mjs. Do not edit. */
export const version = '${version}';
`,
);
